DROP TABLE menus  CASCADE ;
DROP TABLE platos  CASCADE ;
DROP TABLE ingredientes CASCADE ;
DROP TABLE cantidad_ingredientes CASCADE ;
DROP TABLE menu_platos CASCADE ;
DROP SEQUENCE seq_ingredientes;
DROP SEQUENCE seq_platos;
DROP SEQUENCE seq_menus;


CREATE TABLE menus
(
    id VARCHAR(5),
    nombre VARCHAR(100),
    precio NUMERIC(5,2),
    desde DATE,
    hasta DATE,
    CONSTRAINT "PK_MENUS" PRIMARY KEY (id),
    CONSTRAINT "NN_MENUS.NOMBRE" CHECK ( nombre IS NOT NULL ),
    CONSTRAINT "NN_MENUS.DESDE" CHECK ( desde IS NOT NULL ),
    CONSTRAINT "NN_MENUS.HASTA" CHECK ( hasta IS NOT NULL )
);

CREATE TABLE platos
(
    id VARCHAR(5),
    nombre VARCHAR(150),
    descripcion VARCHAR(450),
    precio NUMERIC(5,2),
    tipo VARCHAR(10),
    CONSTRAINT "PK_PLATOS" PRIMARY KEY (id),
    CONSTRAINT "NN_PLATOS.NOMBRE" CHECK ( nombre IS NOT NULL ),
    CONSTRAINT "UK_PLATOS.NOMBRE" UNIQUE (nombre),
    CONSTRAINT "NN_PLATOS.DESCRIPCION" CHECK ( descripcion IS NOT NULL ),
    CONSTRAINT "CH_PLATOS.TIPO" CHECK ( tipo IN('ENTRANTE', 'PRINCIPAL', 'POSTRE', 'INFANTIL') ),
    CONSTRAINT "NN_PLATOS.TIPO" CHECK ( tipo IS NOT NULL )
);
CREATE TABLE ingredientes
(
    id VARCHAR(5),
    nombre VARCHAR(150),
    CONSTRAINT "PK_INGREDIENTES" PRIMARY KEY (id),
    CONSTRAINT "UK_INGREDIENTES.NOMBRE" UNIQUE (nombre),
    CONSTRAINT "NN_INGREDIENTES.NOMBRE" CHECK ( nombre IS NOT NULL )
);
CREATE TABLE menu_platos
(
    id_menu VARCHAR(5),
    id_plato VARCHAR(5),
    CONSTRAINT "FK_MENU_PLATO_MENU" FOREIGN KEY (id_menu) REFERENCES menus(id),
    CONSTRAINT "FK_MENU_PLATO_PLATO" FOREIGN KEY (id_plato) REFERENCES platos(id),
    CONSTRAINT "PK_MENU_PLATOS" PRIMARY KEY (id_menu, id_plato)
);
CREATE TABLE cantidad_ingredientes
(
    id_plato VARCHAR(5),
    id_ingrediente VARCHAR(5),
    cantidad NUMERIC(4),
    unidad VARCHAR(15),
    CONSTRAINT "FK_CANTIDAD_INGREDIENTES_PLATO" FOREIGN KEY (id_plato) REFERENCES platos(id),
    CONSTRAINT "FK_CANTIDAD_INGREDIENTES_INGREDIENTES" FOREIGN KEY (id_ingrediente) REFERENCES ingredientes(id),
    CONSTRAINT "PK_CANTIDAD_INGREDIENTES" PRIMARY KEY (id_plato, id_ingrediente),
    CONSTRAINT "CH_cantidad.UNIDAD" CHECK ( unidad IN('GRAMOS', 'UNIDADES', 'CENTILITROS') )
);


CREATE SEQUENCE seq_menus
    MINVALUE 0
    MAXVALUE 99999
    START WITH 0
    INCREMENT BY 1;
CREATE SEQUENCE seq_platos
    MINVALUE 0
    MAXVALUE 99999
    START WITH 0
    INCREMENT BY 1;
CREATE SEQUENCE seq_ingredientes
    MINVALUE 0
    MAXVALUE 99999
    START WITH 0
    INCREMENT BY 1;

